### ISSUE TITLE
What is the purpose of the publish_cleaned_message() agent?

### ISSUE THREAD

**Issue by taybin** [LaPetiteSouris/KuronoSoshiki#1]
https://github.com/LaPetiteSouris/KuronoSoshiki/blob/21f33478c54e33bccc46ee2d8185c082d1ee3fbd/vodka/vodka.py#L44-L56

Why not have `clean_data()` set `cleaned_user_topic` as its sink directly?

**Comment by LaPetiteSouris** [comment]
At that time I did it on purpose just to test the capacity to sync data between 2 Faust agents.

**Comment by taybin** [comment]
Makes sense. Thank you.
